//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceTeam_Oracle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContextCuong : DbContext
    {
        public ContextCuong()
            : base("name=ContextCuong")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHINHANH> CHINHANHs { get; set; }
        public virtual DbSet<CHITIETHD> CHITIETHDs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<HANGHOA> HANGHOAs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAI> LOAIs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
    
        public virtual int PAGINGHANGHOA(Nullable<decimal> pAGESIZE, Nullable<decimal> pAGEINDEX)
        {
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(decimal));
    
            var pAGEINDEXParameter = pAGEINDEX.HasValue ?
                new ObjectParameter("PAGEINDEX", pAGEINDEX) :
                new ObjectParameter("PAGEINDEX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGINGHANGHOA", pAGESIZEParameter, pAGEINDEXParameter);
        }
    
        public virtual int PAGINGHANGHOA10(ObjectParameter mAHH, ObjectParameter tENHH, ObjectParameter mALOAI, ObjectParameter sOLUONG, ObjectParameter dONGIA, ObjectParameter mOTA, ObjectParameter mANCC)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGINGHANGHOA10", mAHH, tENHH, mALOAI, sOLUONG, dONGIA, mOTA, mANCC);
        }
    
        public virtual int PAGINGHANGHOA2(Nullable<decimal> pAGESIZE, Nullable<decimal> pAGEINDEX)
        {
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(decimal));
    
            var pAGEINDEXParameter = pAGEINDEX.HasValue ?
                new ObjectParameter("PAGEINDEX", pAGEINDEX) :
                new ObjectParameter("PAGEINDEX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGINGHANGHOA2", pAGESIZEParameter, pAGEINDEXParameter);
        }
    
        public virtual int PAGINGHANGHOA23(Nullable<Int32> pAGESIZE, Nullable<decimal> pAGEINDEX)
        {
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(decimal));
    
            var pAGEINDEXParameter = pAGEINDEX.HasValue ?
                new ObjectParameter("PAGEINDEX", pAGEINDEX) :
                new ObjectParameter("PAGEINDEX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGINGHANGHOA23", pAGESIZEParameter, pAGEINDEXParameter);
        }
    }
}
